name = "costgoblin-signup"
main = "src/index.ts"
compatibility_date = "2026-04-07"

routes = [
  { pattern = "costgoblin.com/api/signup", zone_name = "costgoblin.com" }
]

[[kv_namespaces]]
binding = "SIGNUPS"
id = "725d6169dd0f469a9a3167673c34ea83"
