import { join } from 'node:path';
import type { DuckDBConnection } from '@duckdb/node-api';
import { asDimensionId, asProviderName, sqlStringLiteral, type DimensionsConfig, type ProviderSourceSpec } from '@costgoblin/core';
import { fetchRows } from './duckdb-rows.js';

/** Handler tests over the core synthetic fixtures (generated by vitest's
 *  globalSetup): daily data for 2026-01 and 2026-02. */
export const SYNTHETIC_DIR = join(__dirname, '..', '..', '..', '..', 'core', 'src', '__fixtures__', 'synthetic');

// Literal mirror of FIXTURE_PROVIDER_NAME in packages/core/src/__fixtures__/layout.ts.
const FIXTURE_PROVIDER = asProviderName('aws-main');

export const FIXTURE_PROVIDERS: readonly ProviderSourceSpec[] = [
  { name: FIXTURE_PROVIDER, availablePeriods: ['2026-01', '2026-02'] },
];

/** A pinned clock inside the fixture data: 2026-02-20. */
export const FIXTURE_NOW = (): number => Date.UTC(2026, 1, 20);

export const FIXTURE_DIMENSIONS: DimensionsConfig = {
  builtIn: [
    { name: asDimensionId('account'), label: 'Account', field: 'account_id', displayField: 'account_name' },
    { name: asDimensionId('service'), label: 'Service', field: 'service' },
    { name: asDimensionId('charge_category'), label: 'Charge Category', field: 'charge_category' },
  ],
  tags: [{ tagName: 'team', label: 'Team' }],
};

/** The raw fixture rows, for computing expected totals independently of the
 *  code under test. */
export const RAW_FIXTURE = `read_parquet(${sqlStringLiteral(`${SYNTHETIC_DIR}/aws-main/raw/daily-*/*.parquet`)}, union_by_name=true)`;

/** Account id → display name, and its reverse, as the app derives them. */
export async function fixtureAccountMaps(conn: DuckDBConnection): Promise<{
  accountMap: Map<string, string>;
  accountReverseMap: Map<string, readonly string[]>;
}> {
  const rows = await fetchRows(conn, `SELECT DISTINCT SubAccountId AS id, SubAccountName AS name FROM ${RAW_FIXTURE}`);
  const accountMap = new Map<string, string>();
  const reverse = new Map<string, string[]>();
  for (const r of rows) {
    const id = r['id'];
    const name = r['name'];
    if (typeof id !== 'string' || typeof name !== 'string') continue;
    accountMap.set(id, name);
    reverse.set(name, [...(reverse.get(name) ?? []), id]);
  }
  return { accountMap, accountReverseMap: new Map(reverse) };
}
