providers:
  - name: test-aws
    type: aws
    credentials:
      profile: test-profile
    sync:
      daily:
        retentionDays: 365
      hourly:
        retentionDays: 30

defaults:
  periodDays: 30
  costMetric: unblended_cost
  lagDays: 1
