providers:
  - type: aws
    credentials:
      profile: test-profile
    bucketName: cost-goblin-test
    bucketRegion: us-east-1
    reportName: test-cur
    reportPrefix: cur/test-cur
    sync:
      daily:
        retentionDays: 365
      hourly:
        retentionDays: 30

defaults:
  periodDays: 30
  costMetric: unblended_cost
  lagDays: 1
