import type { DateRange, FilterMap } from '../types/query.js';
import type { DimensionId, EntityRef } from '../types/branded.js';

/**
 * Branded type for AI model identifiers (e.g. 'llama3.2:3b', 'mistral:7b').
 * Models are managed by Ollama and identified by name:tag format.
 */
type Brand<T, B extends string> = T & { readonly __brand: B };
export type ModelName = Brand<string, 'ModelName'>;

export function asModelName(value: string): ModelName {
  return value as ModelName;
}

/**
 * Type of insight the AI generates. Each type uses a different prompt template
 * and data shape.
 *   - 'trend-summary'     → plain language summary of cost trends over a date range
 *   - 'optimization'      → recommendations based on spending patterns and Cost Optimization Hub data
 *   - 'conversational'    → free-form answer to natural language cost questions
 */
export type InsightType = 'trend-summary' | 'optimization' | 'conversational';

/**
 * Status of the Ollama service connection. Checked on app launch and before
 * each inference request.
 */
export type OllamaStatus =
  | { readonly state: 'disconnected'; readonly error: string }
  | { readonly state: 'connected'; readonly version: string };

/**
 * Metadata about an available Ollama model. Size is in bytes, format is the
 * quantization format (e.g. 'Q4_0', 'F16').
 */
export interface AIModel {
  readonly name: ModelName;
  readonly size: number;
  readonly format: string;
  readonly family: string;
  readonly modifiedAt: string;
}

/**
 * User preferences for AI features. Stored in state/ai-preferences.json and
 * managed through the CostApi interface.
 */
export interface AIPreferences {
  /** Whether AI features are enabled. Default: false (opt-in). */
  readonly enabled: boolean;
  /** Model to use for inference. If null, uses the first available model. */
  readonly defaultModel: ModelName | null;
  /** Auto-generate trend summaries on Overview page load. Default: false. */
  readonly autoGenerateSummaries: boolean;
  /** Show optimization suggestions in the AI Insights view. Default: true. */
  readonly showOptimizations: boolean;
}

/**
 * Parameters for generating a trend summary insight.
 */
export interface TrendSummaryParams {
  readonly type: 'trend-summary';
  readonly dateRange: DateRange;
  readonly filters: FilterMap;
  readonly groupBy: DimensionId;
}

/**
 * Parameters for generating optimization suggestions.
 */
export interface OptimizationParams {
  readonly type: 'optimization';
  readonly dateRange: DateRange;
  readonly filters: FilterMap;
  /** Minimum cost threshold for including suggestions. */
  readonly minCost: number;
}

/**
 * Parameters for conversational (natural language query) insights.
 */
export interface ConversationalParams {
  readonly type: 'conversational';
  readonly query: string;
  readonly dateRange?: DateRange | undefined;
  readonly filters?: FilterMap | undefined;
}

/**
 * Discriminated union of insight generation parameters.
 */
export type InsightParams = TrendSummaryParams | OptimizationParams | ConversationalParams;

/**
 * A single optimization recommendation generated by the AI.
 */
export interface OptimizationSuggestion {
  /** Short title (e.g. 'Underutilized EC2 instances'). */
  readonly title: string;
  /** Detailed explanation with supporting data. */
  readonly description: string;
  /** Estimated monthly savings if implemented. */
  readonly estimatedSavings: number;
  /** Priority level (high/medium/low). */
  readonly priority: 'high' | 'medium' | 'low';
  /** Optional entity references (e.g. specific accounts or resources). */
  readonly entities?: readonly EntityRef[] | undefined;
}

/**
 * Result of a trend summary insight generation.
 */
export interface TrendSummaryInsight {
  readonly type: 'trend-summary';
  /** Plain language summary of cost trends. */
  readonly summary: string;
  /** Key findings extracted from the data (bullet points). */
  readonly keyFindings: readonly string[];
  /** Cost change direction. */
  readonly trend: 'increasing' | 'decreasing' | 'stable';
}

/**
 * Result of an optimization insight generation.
 */
export interface OptimizationInsight {
  readonly type: 'optimization';
  /** List of optimization recommendations. */
  readonly suggestions: readonly OptimizationSuggestion[];
  /** Total estimated savings across all suggestions. */
  readonly totalEstimatedSavings: number;
}

/**
 * Result of a conversational insight generation.
 */
export interface ConversationalInsight {
  readonly type: 'conversational';
  /** AI's answer to the natural language query. */
  readonly answer: string;
  /** Supporting data references (e.g. 'Based on S3 spend in us-east-1'). */
  readonly supportingData?: readonly string[] | undefined;
}

/**
 * Discriminated union of insight results.
 */
export type InsightResult = TrendSummaryInsight | OptimizationInsight | ConversationalInsight;

/**
 * Wrapper for insight generation results including metadata.
 */
export interface AIInsight {
  readonly result: InsightResult;
  /** Model used for generation. */
  readonly model: ModelName;
  /** Generation timestamp (ISO 8601). */
  readonly generatedAt: string;
  /** Inference time in milliseconds. */
  readonly inferenceTimeMs: number;
}

/**
 * State of an insight generation request. Uses discriminated union to prevent
 * impossible states (no isLoading + data + error combination).
 */
export type InsightGenerationState =
  | { readonly status: 'idle' }
  | { readonly status: 'generating' }
  | { readonly status: 'success'; readonly insight: AIInsight }
  | { readonly status: 'error'; readonly error: string };
